// Code generated from oh-my-pi 18.4.3 (fc671eba3)
// packages/catalog/src/compat/rules/providers/*.kdl — the first `env`
// of every provider that declares one. DO NOT EDIT by hand; regenerate
// when the managed omp version moves.

package logintty

// ompAPIKeyProviders are omp's API-key providers: id, label, env var.
var ompAPIKeyProviders = []APIKeyProvider{
	{ID: "abliteration", Label: "Abliteration", Env: "ABLITERATION_API_KEY"},
	{ID: "aiand", Label: "ai&", Env: "AIAND_API_KEY"},
	{ID: "aimlapi", Label: "AIML API", Env: "AIMLAPI_API_KEY"},
	{ID: "alibaba-coding-plan", Label: "Alibaba Coding Plan", Env: "ALIBABA_CODING_PLAN_API_KEY"},
	{ID: "alibaba-token-plan", Label: "QwenCloud Token Plan", Env: "ALIBABA_TOKEN_PLAN_API_KEY"},
	{ID: "anthropic", Label: "Anthropic", Env: "ANTHROPIC_API_KEY"},
	{ID: "azure", Label: "azure", Env: "AZURE_OPENAI_API_KEY"},
	{ID: "baseten", Label: "Baseten", Env: "BASETEN_API_KEY"},
	{ID: "bedrock-mantle", Label: "bedrock-mantle", Env: "AWS_BEARER_TOKEN_BEDROCK"},
	{ID: "cerebras", Label: "Cerebras", Env: "CEREBRAS_API_KEY"},
	{ID: "charm-hyper", Label: "charm-hyper", Env: "CHARM_HYPER_API_KEY"},
	{ID: "cline-pass", Label: "ClinePass", Env: "CLINE_API_KEY"},
	{ID: "cloudflare-ai-gateway", Label: "Cloudflare AI Gateway", Env: "CLOUDFLARE_AI_GATEWAY_API_KEY"},
	{ID: "commandcode", Label: "Command Code", Env: "COMMAND_CODE_API_KEY"},
	{ID: "coreweave", Label: "CoreWeave Serverless Inference", Env: "COREWEAVE_API_KEY"},
	{ID: "cursor", Label: "Cursor", Env: "CURSOR_ACCESS_TOKEN"},
	{ID: "deepinfra", Label: "DeepInfra", Env: "DEEPINFRA_API_KEY"},
	{ID: "deepseek", Label: "DeepSeek", Env: "DEEPSEEK_API_KEY"},
	{ID: "devin", Label: "Devin", Env: "DEVIN_API_KEY"},
	{ID: "firepass", Label: "firepass", Env: "FIREPASS_API_KEY"},
	{ID: "fireworks", Label: "Fireworks", Env: "FIREWORKS_API_KEY"},
	{ID: "github-copilot", Label: "github-copilot", Env: "COPILOT_GITHUB_TOKEN"},
	{ID: "gitlab-duo-agent", Label: "gitlab-duo-agent", Env: "GITLAB_TOKEN"},
	{ID: "gitlab-duo", Label: "gitlab-duo", Env: "GITLAB_TOKEN"},
	{ID: "gmi-cloud", Label: "GMI Cloud", Env: "GMI_API_KEY"},
	{ID: "google", Label: "google", Env: "GEMINI_API_KEY"},
	{ID: "groq", Label: "groq", Env: "GROQ_API_KEY"},
	{ID: "huggingface", Label: "Hugging Face", Env: "HUGGINGFACE_HUB_TOKEN"},
	{ID: "kilo", Label: "Kilo Gateway", Env: "KILO_API_KEY"},
	{ID: "kimi-code", Label: "Kimi Code", Env: "KIMI_API_KEY"},
	{ID: "litellm", Label: "LiteLLM", Env: "LITELLM_API_KEY"},
	{ID: "lm-studio", Label: "lm-studio", Env: "LM_STUDIO_API_KEY"},
	{ID: "meta", Label: "Meta Model API", Env: "MODEL_API_KEY"},
	{ID: "minimax-code-cn", Label: "minimax-code-cn", Env: "MINIMAX_CODE_CN_API_KEY"},
	{ID: "minimax-code", Label: "minimax-code", Env: "MINIMAX_CODE_API_KEY"},
	{ID: "minimax", Label: "minimax", Env: "MINIMAX_API_KEY"},
	{ID: "mistral", Label: "mistral", Env: "MISTRAL_API_KEY"},
	{ID: "moonshot", Label: "Moonshot", Env: "MOONSHOT_API_KEY"},
	{ID: "nanogpt", Label: "NanoGPT", Env: "NANO_GPT_API_KEY"},
	{ID: "novita", Label: "Novita", Env: "NOVITA_API_KEY"},
	{ID: "nvidia", Label: "NVIDIA", Env: "NVIDIA_API_KEY"},
	{ID: "ollama-cloud", Label: "Ollama Cloud", Env: "OLLAMA_CLOUD_API_KEY"},
	{ID: "ollama", Label: "ollama", Env: "OLLAMA_API_KEY"},
	{ID: "openai-codex", Label: "openai-codex", Env: "OPENAI_CODEX_OAUTH_TOKEN"},
	{ID: "openai", Label: "openai", Env: "OPENAI_API_KEY"},
	{ID: "opencode-go", Label: "opencode-go", Env: "OPENCODE_API_KEY"},
	{ID: "opencode-zen", Label: "opencode-zen", Env: "OPENCODE_API_KEY"},
	{ID: "openrouter", Label: "OpenRouter", Env: "OPENROUTER_API_KEY"},
	{ID: "qianfan", Label: "Qianfan", Env: "QIANFAN_API_KEY"},
	{ID: "qwen-portal", Label: "Qwen Portal", Env: "QWEN_OAUTH_TOKEN"},
	{ID: "sakana", Label: "Sakana AI", Env: "SAKANA_API_KEY"},
	{ID: "siliconflow-cn", Label: "siliconflow-cn", Env: "SILICONFLOW_CN_API_KEY"},
	{ID: "siliconflow", Label: "siliconflow", Env: "SILICONFLOW_API_KEY"},
	{ID: "singularityapi-dev", Label: "singularityapi-dev", Env: "SINGULARITYAPI_DEV_API_KEY"},
	{ID: "singularityapi-tech", Label: "singularityapi-tech", Env: "SINGULARITYAPI_TECH_API_KEY"},
	{ID: "stepfun", Label: "StepFun", Env: "STEPFUN_API_KEY"},
	{ID: "synthetic", Label: "Synthetic", Env: "SYNTHETIC_API_KEY"},
	{ID: "together", Label: "Together", Env: "TOGETHER_API_KEY"},
	{ID: "typesafe", Label: "typesafe", Env: "TYPESAFE_API_KEY"},
	{ID: "umans", Label: "Umans AI Coding Plan", Env: "UMANS_AI_CODING_PLAN_API_KEY"},
	{ID: "venice", Label: "Venice", Env: "VENICE_API_KEY"},
	{ID: "vercel-ai-gateway", Label: "Vercel AI Gateway", Env: "AI_GATEWAY_API_KEY"},
	{ID: "vllm", Label: "vLLM", Env: "VLLM_API_KEY"},
	{ID: "wafer-serverless", Label: "Wafer Serverless", Env: "WAFER_SERVERLESS_API_KEY"},
	{ID: "xai-oauth", Label: "xAI Grok OAuth (SuperGrok)", Env: "XAI_OAUTH_TOKEN"},
	{ID: "xai", Label: "xai", Env: "XAI_API_KEY"},
	{ID: "xiaomi-token-plan-ams", Label: "xiaomi-token-plan-ams", Env: "XIAOMI_TOKEN_PLAN_AMS_API_KEY"},
	{ID: "xiaomi-token-plan-cn", Label: "xiaomi-token-plan-cn", Env: "XIAOMI_TOKEN_PLAN_CN_API_KEY"},
	{ID: "xiaomi-token-plan-sgp", Label: "xiaomi-token-plan-sgp", Env: "XIAOMI_TOKEN_PLAN_SGP_API_KEY"},
	{ID: "xiaomi", Label: "Xiaomi", Env: "XIAOMI_API_KEY"},
	{ID: "yolo-auto", Label: "Yolo-Auto", Env: "YOLO_AUTO_API_KEY"},
	{ID: "zai", Label: "zAI", Env: "ZAI_API_KEY"},
	{ID: "zenmux", Label: "ZenMux", Env: "ZENMUX_API_KEY"},
	{ID: "zhipu-coding-plan", Label: "Zhipu Coding Plan", Env: "ZHIPU_API_KEY"},
}
