//go:build linux || android

package daemon

import (
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"strings"

	"github.com/yogasw/wick/pkg/safeexec"
)

// service_linux.go provides the *headless* backends — only used when
// env.HasGUI returns false (Termux on Android, Linux server / RPi
// without DISPLAY). The GUI path is handled in service.go via
// internal/autostart for desktop Linux with X / Wayland.
//
// Two backends dispatched at runtime:
//
//	Termux on Android → ~/.termux/boot/<appname>-start (shell script)
//	Headless Linux    → ~/.config/systemd/user/<appname>.service
//
// User-scope only to avoid sudo. The trade-off for systemd-user is
// that the daemon stops at logout unless `loginctl enable-linger` is
// run — documented in the status output.

func isTermux() bool {
	if os.Getenv("TERMUX_VERSION") != "" {
		return true
	}
	return pathExists("/data/data/com.termux/files/usr")
}

func installHeadless(p Paths, appName string) error {
	if isTermux() {
		return installTermux(p, appName)
	}
	return installSystemd(p, appName)
}

func uninstallHeadless(appName string) error {
	if isTermux() {
		return uninstallTermux(appName)
	}
	return uninstallSystemd(appName)
}

func statusHeadless(appName string) (ServiceState, error) {
	if isTermux() {
		return termuxStatus(appName)
	}
	return systemdStatus(appName)
}

// ── Termux backend ─────────────────────────────────────────────

func termuxBootPath(appName string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".termux", "boot", appName+"-start"), nil
}

func installTermux(p Paths, appName string) error {
	target, err := termuxBootPath(appName)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	script := fmt.Sprintf("#!/data/data/com.termux/files/usr/bin/sh\n"+
		"# Auto-generated by %s — runs at Termux boot via Termux:Boot addon.\n"+
		"exec %q start\n", appName, p.ExePath)
	return os.WriteFile(target, []byte(script), 0o755)
}

func uninstallTermux(appName string) error {
	target, err := termuxBootPath(appName)
	if err != nil {
		return err
	}
	if !pathExists(target) {
		return ErrNotInstalled
	}
	return os.Remove(target)
}

func termuxStatus(appName string) (ServiceState, error) {
	target, err := termuxBootPath(appName)
	if err != nil {
		return ServiceState{}, err
	}
	st := ServiceState{
		Path:    target,
		Backend: "termux-boot",
		Note:    "requires the Termux:Boot addon installed and granted boot permission",
	}
	st.Installed = pathExists(target)
	return st, nil
}

// ── systemd user backend ───────────────────────────────────────

func systemdUnitPath(appName string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "systemd", "user", appName+".service"), nil
}

// currentUsername returns the login name of the user running this
// process. Server-agnostic — never hardcode "ubuntu"; the daemon runs as
// whatever user installed it (ec2-user, debian, deploy, …) and that is
// the user whose home (~/.claude, ~/.codex, ~/.wick-agent) holds the
// local data. Falls back to $USER, then "" when neither resolves.
func currentUsername() string {
	if u, err := user.Current(); err == nil && u.Username != "" {
		return u.Username
	}
	return os.Getenv("USER")
}

// lingerEnabled reports whether systemd-logind keeps a persistent
// session for username (so its user units survive logout / run at boot
// without anyone logged in). Best-effort: a parse failure or missing
// loginctl reads as "not enabled" so callers err toward offering to
// enable it.
func lingerEnabled(username string) bool {
	if username == "" {
		return false
	}
	out, err := safeexec.Command("loginctl", "show-user", username, "--property=Linger").Output()
	if err != nil {
		return false
	}
	return strings.TrimSpace(string(out)) == "Linger=yes"
}

// enableLinger turns on lingering for username. On modern systemd this
// succeeds without sudo when a user enables it for themselves (polkit
// allows self-linger); on locked-down hosts it needs root. Returns the
// error so the caller can fall back to printing the manual command.
func enableLinger(username string) error {
	if username == "" {
		return fmt.Errorf("could not determine current user")
	}
	return safeexec.Command("loginctl", "enable-linger", username).Run()
}

func installSystemd(p Paths, appName string) error {
	target, err := systemdUnitPath(appName)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	unit := fmt.Sprintf(`[Unit]
Description=%s daemon
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=%s all
Restart=on-failure
RestartSec=5
StandardOutput=append:%s
StandardError=append:%s

[Install]
WantedBy=default.target
`, appName, p.ExePath, p.LogFile, p.LogFile)
	if err := os.WriteFile(target, []byte(unit), 0o644); err != nil {
		return err
	}
	// daemon-reload picks up the new unit. enable wires it into boot.
	// Failures here are non-fatal — user can run the commands manually
	// if the host's systemctl is unavailable.
	_ = safeexec.Command("systemctl", "--user", "daemon-reload").Run()
	_ = safeexec.Command("systemctl", "--user", "enable", appName+".service").Run()

	// Lingering is what makes a user unit survive logout and start at
	// boot with nobody logged in — exactly what a headless server needs.
	// Without it the daemon (and every claude/codex child it spawns) dies
	// the moment the install SSH session ends. Best-effort self-enable:
	// modern systemd allows a user to enable their own linger without
	// sudo; if the host refuses, systemdStatus surfaces the manual
	// command in its Note so the operator isn't left guessing.
	if u := currentUsername(); u != "" && !lingerEnabled(u) {
		_ = enableLinger(u)
	}
	return nil
}

func uninstallSystemd(appName string) error {
	target, err := systemdUnitPath(appName)
	if err != nil {
		return err
	}
	if !pathExists(target) {
		return ErrNotInstalled
	}
	_ = safeexec.Command("systemctl", "--user", "stop", appName+".service").Run()
	_ = safeexec.Command("systemctl", "--user", "disable", appName+".service").Run()
	if err := os.Remove(target); err != nil {
		return err
	}
	_ = safeexec.Command("systemctl", "--user", "daemon-reload").Run()
	return nil
}

func systemdStatus(appName string) (ServiceState, error) {
	target, err := systemdUnitPath(appName)
	if err != nil {
		return ServiceState{}, err
	}
	st := ServiceState{
		Path:    target,
		Backend: "systemd-user",
	}
	// Linger state drives the headline hint: with it on, the unit
	// survives logout and boots unattended; without it, the daemon dies
	// when the login session ends. Report the live state (not a static
	// reminder) and, when off, the exact command to fix it for THIS user
	// — never a hardcoded "ubuntu".
	user := currentUsername()
	if lingerEnabled(user) {
		st.Note = "linger enabled — service survives logout and starts at boot"
	} else {
		cmd := "loginctl enable-linger"
		if user != "" {
			cmd += " " + user
		}
		st.Note = "linger DISABLED — service stops at logout; run: sudo " + cmd
	}
	st.Installed = pathExists(target)
	if st.Installed {
		out, _ := safeexec.Command("systemctl", "--user", "is-active", appName+".service").Output()
		st.Active = strings.TrimSpace(string(out)) == "active"
	}
	return st, nil
}
