// Package session manages on-disk session entries at
// `<BaseDir>/sessions/<id>/`. A session is one Slack thread or one UI
// conversation: routing key, status, agent registry, log files, and an
// optional git worktree linked back to a project's master clone.
//
// Files in this package:
//   - session.go  — Meta + lifecycle (Create/Load/Save/Delete/SwitchProject)
//   - agents.go   — per-session AgentEntry + Add/SetActive
//   - worktree.go — git worktree add/remove (delegates to project pkg)
package session

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/yogasw/wick/internal/agents/config"
	"github.com/yogasw/wick/internal/agents/project"
	"github.com/yogasw/wick/internal/agents/storage"
)

// Origin identifies where the session was first created from. Slack
// threads use thread_ts as the session ID; UI/API sessions use a UUID
// generated by wick.
type Origin string

const (
	OriginSlack Origin = "slack"
	OriginUI    Origin = "ui"
	OriginAPI   Origin = "api"
)

// Status is the high-level pool view: idle (no subprocess), queued
// (waiting for a slot), running (subprocess alive).
type Status string

const (
	StatusIdle    Status = "idle"
	StatusQueued  Status = "queued"
	StatusRunning Status = "running"
)

// Meta is the persisted-on-disk shape of a session. PendingInput is
// the message buffer that survives wick restart so a session that was
// queued at shutdown gets its messages drained on next boot.
type Meta struct {
	Project      string    `json:"project,omitempty"`
	Origin       Origin    `json:"origin"`
	ChannelID    string    `json:"channel_id,omitempty"`
	ActiveAgent  string    `json:"active_agent,omitempty"`
	Status       Status    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	LastActive   time.Time `json:"last_active"`
	PendingInput []string  `json:"pending_input,omitempty"`
}

// Session is the in-memory view: ID + meta + agent registry. Mirrors
// the trio of files at sessions/<id>/.
type Session struct {
	ID     string       `json:"id"`
	Meta   Meta         `json:"meta"`
	Agents []AgentEntry `json:"agents"`
}

// CreateOptions describes a new session. ProjectName is optional — a
// session may be created before it's attached to a project.
type CreateOptions struct {
	ID        string
	Project   string
	Origin    Origin
	ChannelID string
	// PresetSnapshot is the preset body copied into the session's
	// agent.md at creation time. Empty = caller will populate later
	// (e.g. when first agent is added). The design says we always
	// snapshot at session creation so re-opening a session never drifts
	// because someone edited the preset since.
	PresetSnapshot string
}

// Create materializes sessions/<id>/: meta.json, agents.json (empty
// array), agent.md snapshot, and the git worktree linking back to the
// project's master clone (if attached).
func Create(ctx context.Context, layout config.Layout, opt CreateOptions) (Session, error) {
	if err := storage.ValidateSessionID(opt.ID); err != nil {
		return Session{}, err
	}
	if opt.Origin == "" {
		opt.Origin = OriginUI
	}
	dir := layout.SessionDir(opt.ID)
	if storage.PathExists(dir) {
		return Session{}, fmt.Errorf("session %q already exists", opt.ID)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return Session{}, err
	}

	now := time.Now().UTC()
	meta := Meta{
		Project:    opt.Project,
		Origin:     opt.Origin,
		ChannelID:  opt.ChannelID,
		Status:     StatusIdle,
		CreatedAt:  now,
		LastActive: now,
	}
	if err := storage.WriteJSON(layout.SessionMeta(opt.ID), &meta); err != nil {
		_ = os.RemoveAll(dir)
		return Session{}, err
	}
	if err := storage.WriteJSON(layout.SessionAgents(opt.ID), []AgentEntry{}); err != nil {
		_ = os.RemoveAll(dir)
		return Session{}, err
	}
	if opt.PresetSnapshot != "" {
		if err := os.WriteFile(layout.SessionAgentMD(opt.ID), []byte(opt.PresetSnapshot), 0o644); err != nil {
			_ = os.RemoveAll(dir)
			return Session{}, err
		}
	}

	if opt.Project != "" {
		if !project.Exists(layout, opt.Project) {
			_ = os.RemoveAll(dir)
			return Session{}, fmt.Errorf("project %q not found", opt.Project)
		}
		if err := addWorktree(ctx, layout, opt.Project, opt.ID); err != nil {
			_ = os.RemoveAll(dir)
			return Session{}, err
		}
	}

	return Session{ID: opt.ID, Meta: meta, Agents: []AgentEntry{}}, nil
}

// Load reads meta.json + agents.json. Missing agents.json is treated
// as an empty list.
func Load(layout config.Layout, id string) (Session, error) {
	if err := storage.ValidateSessionID(id); err != nil {
		return Session{}, err
	}
	var meta Meta
	if err := storage.ReadJSON(layout.SessionMeta(id), &meta); err != nil {
		return Session{}, err
	}
	var agents []AgentEntry
	if storage.PathExists(layout.SessionAgents(id)) {
		if err := storage.ReadJSON(layout.SessionAgents(id), &agents); err != nil {
			return Session{}, err
		}
	}
	return Session{ID: id, Meta: meta, Agents: agents}, nil
}

// SaveMeta atomically rewrites sessions/<id>/meta.json.
func SaveMeta(layout config.Layout, id string, meta Meta) error {
	if err := storage.ValidateSessionID(id); err != nil {
		return err
	}
	if !storage.PathExists(layout.SessionDir(id)) {
		return fmt.Errorf("session %q not found", id)
	}
	return storage.WriteJSON(layout.SessionMeta(id), &meta)
}

// List returns every session ID, sorted.
func List(layout config.Layout) ([]string, error) {
	return storage.ScanDirNames(layout.SessionsDir())
}

// Delete removes the session worktree (if attached) and the session
// folder. If worktree removal fails we still try to delete the folder
// so a corrupt worktree state can't block cleanup forever — caller can
// `git worktree prune` later.
func Delete(ctx context.Context, layout config.Layout, id string) error {
	if err := storage.ValidateSessionID(id); err != nil {
		return err
	}
	sess, err := Load(layout, id)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	if sess.Meta.Project != "" && storage.PathExists(layout.SessionWorkspace(id)) {
		_ = removeWorktree(ctx, layout, sess.Meta.Project, id)
	}
	return os.RemoveAll(layout.SessionDir(id))
}

// SwitchProject moves a session to a different project: removes the
// old worktree, adds a new one against the target project. Conversation
// and agent registry are preserved (the session keeps its identity);
// only the workspace files change.
func SwitchProject(ctx context.Context, layout config.Layout, id, newProject string) error {
	if !project.Exists(layout, newProject) {
		return fmt.Errorf("project %q not found", newProject)
	}
	sess, err := Load(layout, id)
	if err != nil {
		return err
	}
	if sess.Meta.Project == newProject {
		return nil
	}
	if sess.Meta.Project != "" && storage.PathExists(layout.SessionWorkspace(id)) {
		_ = removeWorktree(ctx, layout, sess.Meta.Project, id)
	}
	if err := addWorktree(ctx, layout, newProject, id); err != nil {
		return err
	}
	sess.Meta.Project = newProject
	sess.Meta.LastActive = time.Now().UTC()
	return SaveMeta(layout, id, sess.Meta)
}
