// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package session_init

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Inspector is the parameters-tab partial for the session_init node.
// editor.js shows the block when the selected node's type matches
// data-node-type, and hides every other panel. The partial owns its
// own DOM IDs (ins-session-mode, ins-session-id, ins-session-regen)
// so the JS module in inspector.js can read/write state without
// going through editor.js.
func Inspector() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"wf-inspector-panel hidden\" data-node-type=\"session_init\"><label class=\"block text-xs font-medium text-black-800 dark:text-black-600 mb-1 mt-3\">Session sharing</label> <select id=\"ins-session-mode\" class=\"wf-input\"><option value=\"workflow_run\">Reuse in run — agents share subprocess within 1 run (default)</option> <option value=\"workflow_global\">Reuse across runs — agent remembers history forever</option> <option value=\"new\">Fresh each call — no context carry, new subprocess every node</option> <option value=\"custom\">Custom ID — literal or template</option></select><div id=\"ins-session-custom-wrap\" class=\"hidden mt-3\"><label class=\"block text-xs font-medium text-black-800 dark:text-black-600 mb-1\">Session ID</label><div class=\"flex gap-2\"><input id=\"ins-session-id\" type=\"text\" placeholder=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue("literal or {{.Event.Payload.thread_ts}}")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/tools/agents/workflow/nodes/session_init/inspector.templ`, Line: 21, Col: 98}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"wf-input font-mono flex-1\"> <button type=\"button\" id=\"ins-session-regen\" class=\"rounded-lg bg-violet-500/15 dark:bg-violet-500/20 px-2 text-xs font-medium text-violet-700 dark:text-violet-300 hover:bg-violet-500/25 dark:hover:bg-violet-500/30 transition-colors\" title=\"Generate new UUID into the input\">Auto</button></div><div class=\"mt-1 text-[11px] text-black-700 dark:text-black-600\">Literal string baked into YAML, or template rendered at runtime.</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
