// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/yogasw/wick/internal/entity"

func customDNSValue(dnsServers string) string {
	if dnsServers == "" || dnsServers == "8.8.8.8,8.8.4.4" || dnsServers == "1.1.1.1,1.0.0.1" {
		return ""
	}
	return dnsServers
}

func NetworkPage(dnsServers string, user *entity.User) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"mx-auto w-full max-w-container px-6 py-8\"><div class=\"flex items-center gap-2 text-sm text-black-700 dark:text-black-600\"><a href=\"/admin/advanced\" class=\"hover:text-green-600\">Advanced</a> <span>/</span><span class=\"text-black-900 dark:text-white-100\">Network & DNS</span></div><h1 class=\"mt-2 text-[1.375rem] font-semibold text-black-900 dark:text-white-100\">Network & DNS</h1><p class=\"mt-1 text-sm text-black-800 dark:text-black-600\">Runtime network compatibility settings for connector plugins.</p><form method=\"POST\" action=\"/admin/advanced/network\" class=\"mt-6 max-w-2xl rounded-xl border border-white-300 bg-white-100 p-6 shadow-sm dark:border-navy-600 dark:bg-navy-700\"><label for=\"dns_provider\" class=\"block text-sm font-medium text-black-900 dark:text-white-100\">Termux plugin DNS provider</label><p class=\"mt-1 text-xs text-black-700 dark:text-black-600\">Used only by connector plugins running on Termux. Google DNS is the default.</p><select id=\"dns_provider\" name=\"dns_provider\" class=\"mt-4 w-full rounded-lg border border-white-400 bg-white-100 px-3 py-2 text-sm text-black-900 outline-none focus:border-green-500 dark:border-navy-600 dark:bg-navy-800 dark:text-white-100\"><option value=\"google\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if dnsServers == "" || dnsServers == "8.8.8.8,8.8.4.4" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, ">Google DNS — 8.8.8.8 / 8.8.4.4</option> <option value=\"cloudflare\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if dnsServers == "1.1.1.1,1.0.0.1" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, ">Cloudflare DNS — 1.1.1.1 / 1.0.0.1</option> <option value=\"custom\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if dnsServers != "" && dnsServers != "8.8.8.8,8.8.4.4" && dnsServers != "1.1.1.1,1.0.0.1" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, ">Custom DNS</option></select> <label for=\"dns_custom\" class=\"mt-4 block text-sm font-medium text-black-900 dark:text-white-100\">Custom DNS addresses</label><p class=\"mt-1 text-xs text-black-700 dark:text-black-600\">Used only when Custom DNS is selected. Enter 1–4 IP addresses separated by commas or spaces.</p><input id=\"dns_custom\" name=\"dns_custom\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(customDNSValue(dnsServers))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/admin/view/network.templ`, Line: 31, Col: 79}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" placeholder=\"9.9.9.9,149.112.112.112\" class=\"mt-2 w-full rounded-lg border border-white-400 bg-white-100 px-3 py-2 text-sm text-black-900 outline-none focus:border-green-500 dark:border-navy-600 dark:bg-navy-800 dark:text-white-100\"><div class=\"mt-4 flex items-center gap-3\"><button type=\"submit\" class=\"rounded-lg bg-green-500 px-4 py-2 text-sm font-medium text-white-100 hover:bg-green-600\">Save DNS settings</button> <span class=\"text-xs text-black-700 dark:text-black-600\">Restart active plugin processes after changing this value.</span></div></form></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = AdminLayout("Admin · Network & DNS", "advanced", user).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
