// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/yogasw/wick/internal/entity"
	"github.com/yogasw/wick/internal/pkg/ui"
)

func ProfilePage(user *entity.User, errMsg string, success bool, prefsSaved bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"mx-auto w-full max-w-container px-6 py-8\"><h1 class=\"text-[1.375rem] font-semibold text-black-900 dark:text-white-100\">Account</h1><p class=\"mt-1 text-sm text-black-800 dark:text-black-600\">Your password and display preferences.</p><div class=\"mt-6 grid grid-cols-1 gap-6 lg:grid-cols-2\"><!-- Password section --><div class=\"rounded-xl border border-white-300 dark:border-navy-600 bg-white-100 dark:bg-navy-700 p-6 shadow-sm\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if user.PasswordHash != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<h2 class=\"text-base font-semibold text-black-900 dark:text-white-100\">Change password</h2><p class=\"mt-1 text-sm text-black-800 dark:text-black-600\">Update your login password.</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h2 class=\"text-base font-semibold text-black-900 dark:text-white-100\">Set a password</h2><p class=\"mt-1 text-sm text-black-800 dark:text-black-600\">Set a password so you can sign in without Google OAuth.</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if success {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"mt-4 rounded-lg border border-pos-200 bg-pos-100 px-4 py-3 text-sm text-pos-400\">Password updated successfully.</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if errMsg != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"mt-4 rounded-lg border border-neg-200 bg-neg-100 px-4 py-3 text-sm text-neg-400\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(errMsg)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/login/view/profile.templ`, Line: 30, Col: 15}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<form action=\"/profile/password\" method=\"POST\" class=\"mt-5 flex flex-col gap-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if user.PasswordHash != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div class=\"flex flex-col gap-1.5\"><label for=\"current_password\" class=\"text-sm font-medium text-black-900 dark:text-white-100\">Current password</label> <input id=\"current_password\" name=\"current_password\" type=\"password\" required autocomplete=\"current-password\" placeholder=\"••••••••\" class=\"rounded-lg border border-white-400 dark:border-navy-600 bg-white-100 dark:bg-navy-800 px-3 py-2.5 text-sm text-black-900 dark:text-white-100 placeholder:text-black-700 outline-none transition-colors focus:border-green-500 focus:ring-2 focus:ring-green-200 dark:focus:ring-green-800\"></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"flex flex-col gap-1.5\"><label for=\"new_password\" class=\"text-sm font-medium text-black-900 dark:text-white-100\">New password</label> <input id=\"new_password\" name=\"new_password\" type=\"password\" required minlength=\"8\" autocomplete=\"new-password\" placeholder=\"Min. 8 characters\" class=\"rounded-lg border border-white-400 dark:border-navy-600 bg-white-100 dark:bg-navy-800 px-3 py-2.5 text-sm text-black-900 dark:text-white-100 placeholder:text-black-700 outline-none transition-colors focus:border-green-500 focus:ring-2 focus:ring-green-200 dark:focus:ring-green-800\"></div><div class=\"flex flex-col gap-1.5\"><label for=\"confirm_password\" class=\"text-sm font-medium text-black-900 dark:text-white-100\">Confirm new password</label> <input id=\"confirm_password\" name=\"confirm_password\" type=\"password\" required minlength=\"8\" autocomplete=\"new-password\" placeholder=\"••••••••\" class=\"rounded-lg border border-white-400 dark:border-navy-600 bg-white-100 dark:bg-navy-800 px-3 py-2.5 text-sm text-black-900 dark:text-white-100 placeholder:text-black-700 outline-none transition-colors focus:border-green-500 focus:ring-2 focus:ring-green-200 dark:focus:ring-green-800\"></div><div class=\"flex justify-end\"><button type=\"submit\" class=\"rounded-lg bg-green-500 px-5 py-2.5 text-sm font-medium text-white-100 transition-colors hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-prog-300\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if user.PasswordHash != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "Update password")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "Set password")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</button></div></form></div><!-- Display preferences -->")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			homeView := user.Metadata.HomeViewOrDefault()
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<div class=\"rounded-xl border border-white-300 dark:border-navy-600 bg-white-100 dark:bg-navy-700 p-6 shadow-sm\"><h2 class=\"text-base font-semibold text-black-900 dark:text-white-100\">Display preferences</h2><p class=\"mt-1 text-sm text-black-800 dark:text-black-600\">Choose how the home tool grid is rendered.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if prefsSaved {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<div class=\"mt-4 rounded-lg border border-pos-200 bg-pos-100 px-4 py-3 text-sm text-pos-400\">Preferences saved.</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<form action=\"/profile/preferences\" method=\"POST\" class=\"mt-5 flex flex-col gap-3\"><label class=\"flex cursor-pointer items-start gap-3 rounded-lg border border-white-400 dark:border-navy-600 bg-white-100 dark:bg-navy-800 p-4 transition-colors hover:border-green-400\"><input type=\"radio\" name=\"home_view\" value=\"compact\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if homeView == "compact" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, " checked")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, " class=\"mt-0.5 h-4 w-4 accent-green-500\"> <span class=\"flex flex-col\"><span class=\"text-sm font-medium text-black-900 dark:text-white-100\">Compact</span> <span class=\"text-xs text-black-700 dark:text-black-600\">Small icon-and-name cards — fit more tools on screen.</span></span></label> <label class=\"flex cursor-pointer items-start gap-3 rounded-lg border border-white-400 dark:border-navy-600 bg-white-100 dark:bg-navy-800 p-4 transition-colors hover:border-green-400\"><input type=\"radio\" name=\"home_view\" value=\"detailed\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if homeView == "detailed" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, " checked")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, " class=\"mt-0.5 h-4 w-4 accent-green-500\"> <span class=\"flex flex-col\"><span class=\"text-sm font-medium text-black-900 dark:text-white-100\">Detailed</span> <span class=\"text-xs text-black-700 dark:text-black-600\">Larger cards with full names and descriptions.</span></span></label><div class=\"flex justify-end\"><button type=\"submit\" class=\"rounded-lg bg-green-500 px-5 py-2.5 text-sm font-medium text-white-100 transition-colors hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-prog-300\">Save preferences</button></div></form></div></div></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = ui.ProfileLayout("Profile", ui.ProfileTabAccount, user).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
